/*
 * FinFeedAPI Stock REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Model;
using APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Client;
using System.Reflection;

namespace APIBricks.FinFeedAPI.STOCKAPI.REST.V1.Test.Model
{
    /// <summary>
    ///  Class for testing AdminSystemEventModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminSystemEventModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminSystemEventModel
        //private AdminSystemEventModel instance;

        public AdminSystemEventModelTests()
        {
            // TODO uncomment below to create an instance of AdminSystemEventModel
            //instance = new AdminSystemEventModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminSystemEventModel
        /// </summary>
        [Fact]
        public void AdminSystemEventModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminSystemEventModel
            //Assert.IsType<AdminSystemEventModel>(instance);
        }

        /// <summary>
        /// Test the property 'TimestampNanos'
        /// </summary>
        [Fact]
        public void TimestampNanosTest()
        {
            // TODO unit test for the property 'TimestampNanos'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'SystemEvent'
        /// </summary>
        [Fact]
        public void SystemEventTest()
        {
            // TODO unit test for the property 'SystemEvent'
        }

        /// <summary>
        /// Test the property 'SystemEventCode'
        /// </summary>
        [Fact]
        public void SystemEventCodeTest()
        {
            // TODO unit test for the property 'SystemEventCode'
        }

        /// <summary>
        /// Test the property 'SystemEventText'
        /// </summary>
        [Fact]
        public void SystemEventTextTest()
        {
            // TODO unit test for the property 'SystemEventText'
        }

        /// <summary>
        /// Test the property 'IsSystemEventStartOfMessages'
        /// </summary>
        [Fact]
        public void IsSystemEventStartOfMessagesTest()
        {
            // TODO unit test for the property 'IsSystemEventStartOfMessages'
        }

        /// <summary>
        /// Test the property 'IsSystemEventStartOfSystemHours'
        /// </summary>
        [Fact]
        public void IsSystemEventStartOfSystemHoursTest()
        {
            // TODO unit test for the property 'IsSystemEventStartOfSystemHours'
        }

        /// <summary>
        /// Test the property 'IsSystemEventStartOfRegularMarketHours'
        /// </summary>
        [Fact]
        public void IsSystemEventStartOfRegularMarketHoursTest()
        {
            // TODO unit test for the property 'IsSystemEventStartOfRegularMarketHours'
        }

        /// <summary>
        /// Test the property 'IsSystemEventEndOfRegularMarketHours'
        /// </summary>
        [Fact]
        public void IsSystemEventEndOfRegularMarketHoursTest()
        {
            // TODO unit test for the property 'IsSystemEventEndOfRegularMarketHours'
        }

        /// <summary>
        /// Test the property 'IsSystemEventEndOfSystemHours'
        /// </summary>
        [Fact]
        public void IsSystemEventEndOfSystemHoursTest()
        {
            // TODO unit test for the property 'IsSystemEventEndOfSystemHours'
        }

        /// <summary>
        /// Test the property 'IsSystemEventEndOfMessages'
        /// </summary>
        [Fact]
        public void IsSystemEventEndOfMessagesTest()
        {
            // TODO unit test for the property 'IsSystemEventEndOfMessages'
        }
    }
}
