=begin comment

FX Historical REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@apibricks.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::V1Asset;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use WWW::OpenAPIClient::Object::V1ChainNetworkAddress;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#Represents an asset.
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

FX Historical REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@apibricks.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => 'Represents an asset.',
                                  class => 'V1Asset',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'asset_id' => {
        datatype => 'string',
        base_name => 'asset_id',
        description => 'Gets or sets the asset ID.',
        format => '',
        read_only => '',
            },
    'name' => {
        datatype => 'string',
        base_name => 'name',
        description => 'Gets or sets the name of the asset.',
        format => '',
        read_only => '',
            },
    'type_is_crypto' => {
        datatype => 'int',
        base_name => 'type_is_crypto',
        description => 'Gets or sets a value indicating whether the asset is a cryptocurrency.',
        format => '',
        read_only => '',
            },
    'data_quote_start' => {
        datatype => 'DATE_TIME',
        base_name => 'data_quote_start',
        description => 'Gets or sets the start date of quote data.',
        format => '',
        read_only => '',
            },
    'data_quote_end' => {
        datatype => 'DATE_TIME',
        base_name => 'data_quote_end',
        description => 'Gets or sets the end date of quote data.',
        format => '',
        read_only => '',
            },
    'data_orderbook_start' => {
        datatype => 'DATE_TIME',
        base_name => 'data_orderbook_start',
        description => 'Gets or sets the start date of order book data.',
        format => '',
        read_only => '',
            },
    'data_orderbook_end' => {
        datatype => 'DATE_TIME',
        base_name => 'data_orderbook_end',
        description => 'Gets or sets the end date of order book data.',
        format => '',
        read_only => '',
            },
    'data_trade_start' => {
        datatype => 'DATE_TIME',
        base_name => 'data_trade_start',
        description => 'Gets or sets the start date of trade data.',
        format => '',
        read_only => '',
            },
    'data_trade_end' => {
        datatype => 'DATE_TIME',
        base_name => 'data_trade_end',
        description => 'Gets or sets the end date of trade data.',
        format => '',
        read_only => '',
            },
    'data_symbols_count' => {
        datatype => 'int',
        base_name => 'data_symbols_count',
        description => 'Gets or sets the number of symbols.',
        format => '',
        read_only => '',
            },
    'volume_1hrs_usd' => {
        datatype => 'double',
        base_name => 'volume_1hrs_usd',
        description => 'Gets or sets the USD volume in the last 1 hour.',
        format => '',
        read_only => '',
            },
    'volume_1day_usd' => {
        datatype => 'double',
        base_name => 'volume_1day_usd',
        description => 'Gets or sets the USD volume in the last 1 day.',
        format => '',
        read_only => '',
            },
    'volume_1mth_usd' => {
        datatype => 'double',
        base_name => 'volume_1mth_usd',
        description => 'Gets or sets the USD volume in the last 1 month.',
        format => '',
        read_only => '',
            },
    'price_usd' => {
        datatype => 'double',
        base_name => 'price_usd',
        description => 'Gets or sets the USD price of the asset.',
        format => '',
        read_only => '',
            },
    'id_icon' => {
        datatype => 'string',
        base_name => 'id_icon',
        description => 'Gets or sets the ID of the icon for the asset.',
        format => '',
        read_only => '',
            },
    'supply_current' => {
        datatype => 'double',
        base_name => 'supply_current',
        description => 'Gets or sets the current supply of the asset.',
        format => '',
        read_only => '',
            },
    'supply_total' => {
        datatype => 'double',
        base_name => 'supply_total',
        description => 'Gets or sets the total supply of the asset.',
        format => '',
        read_only => '',
            },
    'supply_max' => {
        datatype => 'double',
        base_name => 'supply_max',
        description => 'Gets or sets the maximum supply of the asset.',
        format => '',
        read_only => '',
            },
    'chain_addresses' => {
        datatype => 'ARRAY[V1ChainNetworkAddress]',
        base_name => 'chain_addresses',
        description => '',
        format => '',
        read_only => '',
            },
    'data_start' => {
        datatype => 'string',
        base_name => 'data_start',
        description => '',
        format => '',
        read_only => '',
            },
    'data_end' => {
        datatype => 'string',
        base_name => 'data_end',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'asset_id' => 'string',
    'name' => 'string',
    'type_is_crypto' => 'int',
    'data_quote_start' => 'DATE_TIME',
    'data_quote_end' => 'DATE_TIME',
    'data_orderbook_start' => 'DATE_TIME',
    'data_orderbook_end' => 'DATE_TIME',
    'data_trade_start' => 'DATE_TIME',
    'data_trade_end' => 'DATE_TIME',
    'data_symbols_count' => 'int',
    'volume_1hrs_usd' => 'double',
    'volume_1day_usd' => 'double',
    'volume_1mth_usd' => 'double',
    'price_usd' => 'double',
    'id_icon' => 'string',
    'supply_current' => 'double',
    'supply_total' => 'double',
    'supply_max' => 'double',
    'chain_addresses' => 'ARRAY[V1ChainNetworkAddress]',
    'data_start' => 'string',
    'data_end' => 'string'
} );

__PACKAGE__->attribute_map( {
    'asset_id' => 'asset_id',
    'name' => 'name',
    'type_is_crypto' => 'type_is_crypto',
    'data_quote_start' => 'data_quote_start',
    'data_quote_end' => 'data_quote_end',
    'data_orderbook_start' => 'data_orderbook_start',
    'data_orderbook_end' => 'data_orderbook_end',
    'data_trade_start' => 'data_trade_start',
    'data_trade_end' => 'data_trade_end',
    'data_symbols_count' => 'data_symbols_count',
    'volume_1hrs_usd' => 'volume_1hrs_usd',
    'volume_1day_usd' => 'volume_1day_usd',
    'volume_1mth_usd' => 'volume_1mth_usd',
    'price_usd' => 'price_usd',
    'id_icon' => 'id_icon',
    'supply_current' => 'supply_current',
    'supply_total' => 'supply_total',
    'supply_max' => 'supply_max',
    'chain_addresses' => 'chain_addresses',
    'data_start' => 'data_start',
    'data_end' => 'data_end'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
