-module(openapi_admin_auction_information_model).

-export([encode/1]).

-export_type([openapi_admin_auction_information_model/0]).

-type openapi_admin_auction_information_model() ::
    #{ 'symbol' => binary(),
       'timestamp_nanos' => integer(),
       'timestamp' => openapi_date_time:openapi_date_time(),
       'auction_type' => integer(),
       'auction_type_code' => binary(),
       'auction_type_text' => binary(),
       'is_auction_type_opening' => boolean(),
       'is_auction_type_closing' => boolean(),
       'is_auction_type_ipo' => boolean(),
       'is_auction_type_halt' => boolean(),
       'is_auction_type_volatility' => boolean(),
       'paired_shares' => integer(),
       'reference_price' => float(),
       'indicative_clearing_price' => float(),
       'imbalance_shares' => integer(),
       'imbalance_side' => integer(),
       'imbalance_side_code' => binary(),
       'imbalance_side_text' => binary(),
       'is_imbalance_side_buy' => boolean(),
       'is_imbalance_side_sell' => boolean(),
       'is_imbalance_side_none' => boolean(),
       'extension_number' => integer(),
       'scheduled_auction_time_seconds' => integer(),
       'scheduled_auction_time' => openapi_date_time:openapi_date_time(),
       'auction_book_clearing_price' => float(),
       'collar_reference_price' => float(),
       'lower_auction_collar' => float(),
       'upper_auction_collar' => float()
     }.

encode(#{ 'symbol' := Symbol,
          'timestamp_nanos' := TimestampNanos,
          'timestamp' := Timestamp,
          'auction_type' := AuctionType,
          'auction_type_code' := AuctionTypeCode,
          'auction_type_text' := AuctionTypeText,
          'is_auction_type_opening' := IsAuctionTypeOpening,
          'is_auction_type_closing' := IsAuctionTypeClosing,
          'is_auction_type_ipo' := IsAuctionTypeIpo,
          'is_auction_type_halt' := IsAuctionTypeHalt,
          'is_auction_type_volatility' := IsAuctionTypeVolatility,
          'paired_shares' := PairedShares,
          'reference_price' := ReferencePrice,
          'indicative_clearing_price' := IndicativeClearingPrice,
          'imbalance_shares' := ImbalanceShares,
          'imbalance_side' := ImbalanceSide,
          'imbalance_side_code' := ImbalanceSideCode,
          'imbalance_side_text' := ImbalanceSideText,
          'is_imbalance_side_buy' := IsImbalanceSideBuy,
          'is_imbalance_side_sell' := IsImbalanceSideSell,
          'is_imbalance_side_none' := IsImbalanceSideNone,
          'extension_number' := ExtensionNumber,
          'scheduled_auction_time_seconds' := ScheduledAuctionTimeSeconds,
          'scheduled_auction_time' := ScheduledAuctionTime,
          'auction_book_clearing_price' := AuctionBookClearingPrice,
          'collar_reference_price' := CollarReferencePrice,
          'lower_auction_collar' := LowerAuctionCollar,
          'upper_auction_collar' := UpperAuctionCollar
        }) ->
    #{ 'symbol' => Symbol,
       'timestamp_nanos' => TimestampNanos,
       'timestamp' => Timestamp,
       'auction_type' => AuctionType,
       'auction_type_code' => AuctionTypeCode,
       'auction_type_text' => AuctionTypeText,
       'is_auction_type_opening' => IsAuctionTypeOpening,
       'is_auction_type_closing' => IsAuctionTypeClosing,
       'is_auction_type_ipo' => IsAuctionTypeIpo,
       'is_auction_type_halt' => IsAuctionTypeHalt,
       'is_auction_type_volatility' => IsAuctionTypeVolatility,
       'paired_shares' => PairedShares,
       'reference_price' => ReferencePrice,
       'indicative_clearing_price' => IndicativeClearingPrice,
       'imbalance_shares' => ImbalanceShares,
       'imbalance_side' => ImbalanceSide,
       'imbalance_side_code' => ImbalanceSideCode,
       'imbalance_side_text' => ImbalanceSideText,
       'is_imbalance_side_buy' => IsImbalanceSideBuy,
       'is_imbalance_side_sell' => IsImbalanceSideSell,
       'is_imbalance_side_none' => IsImbalanceSideNone,
       'extension_number' => ExtensionNumber,
       'scheduled_auction_time_seconds' => ScheduledAuctionTimeSeconds,
       'scheduled_auction_time' => ScheduledAuctionTime,
       'auction_book_clearing_price' => AuctionBookClearingPrice,
       'collar_reference_price' => CollarReferencePrice,
       'lower_auction_collar' => LowerAuctionCollar,
       'upper_auction_collar' => UpperAuctionCollar
     }.
