export * from './ExchangeRatesApi';
import { ExchangeRatesApi } from './ExchangeRatesApi';
export * from './ExternalMetricsApi';
import { ExternalMetricsApi } from './ExternalMetricsApi';
export * from './MetadataApi';
import { MetadataApi } from './MetadataApi';
export * from './MetricsApi';
import { MetricsApi } from './MetricsApi';
export * from './OhlcvApi';
import { OhlcvApi } from './OhlcvApi';
export * from './OptionsApi';
import { OptionsApi } from './OptionsApi';
export * from './OrderBookApi';
import { OrderBookApi } from './OrderBookApi';
export * from './OrderBookL3Api';
import { OrderBookL3Api } from './OrderBookL3Api';
export * from './QuotesApi';
import { QuotesApi } from './QuotesApi';
export * from './TradesApi';
import { TradesApi } from './TradesApi';
export const APIS = [ExchangeRatesApi, ExternalMetricsApi, MetadataApi, MetricsApi, OhlcvApi, OptionsApi, OrderBookApi, OrderBookL3Api, QuotesApi, TradesApi];
