export * from './ExchangeRatesApi';
import { ExchangeRatesApi } from './ExchangeRatesApi';
export * from './MetadataApi';
import { MetadataApi } from './MetadataApi';
export * from './MetricsV1Api';
import { MetricsV1Api } from './MetricsV1Api';
export * from './MetricsV2Api';
import { MetricsV2Api } from './MetricsV2Api';
export * from './OhlcvApi';
import { OhlcvApi } from './OhlcvApi';
export * from './OptionsApi';
import { OptionsApi } from './OptionsApi';
export * from './OrderBookApi';
import { OrderBookApi } from './OrderBookApi';
export * from './OrderBookL3Api';
import { OrderBookL3Api } from './OrderBookL3Api';
export * from './QuotesApi';
import { QuotesApi } from './QuotesApi';
export * from './TradesApi';
import { TradesApi } from './TradesApi';
export const APIS = [ExchangeRatesApi, MetadataApi, MetricsV1Api, MetricsV2Api, OhlcvApi, OptionsApi, OrderBookApi, OrderBookL3Api, QuotesApi, TradesApi];
