# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RESTAPI.Model.V1ExternalExchange do
  @moduledoc """
  Represents an exchange with external mapping for metrics.
  """

  @derive JSON.Encoder
  defstruct [
    :exchange_id,
    :external_name,
    :description,
    :source_id
  ]

  @type t :: %__MODULE__{
    :exchange_id => String.t | nil,
    :external_name => String.t | nil,
    :description => String.t | nil,
    :source_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

