# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RESTAPI.Model.V1ExchangeRates do
  @moduledoc """
  Represents exchange rates for a specific base asset.
  """

  @derive JSON.Encoder
  defstruct [
    :asset_id_base,
    :rates
  ]

  @type t :: %__MODULE__{
    :asset_id_base => String.t | nil,
    :rates => [RESTAPI.Model.V1ExchangeRatesRate.t] | nil
  }

  alias RESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rates, :list, RESTAPI.Model.V1ExchangeRatesRate)
  end
end

