# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RESTAPI.Model.V1MetricInfo do
  @moduledoc """
  Represents a metric information.
  """

  @derive JSON.Encoder
  defstruct [
    :metric_id,
    :description,
    :source_id
  ]

  @type t :: %__MODULE__{
    :metric_id => String.t | nil,
    :description => String.t | nil,
    :source_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

