// tslint:disable
/**
 * REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    OptionsStrike,
} from './';

/**
 * Represents an option exchange group data model.
 * @export
 * @interface OptionsOptionExchangeGroup
 */
export interface OptionsOptionExchangeGroup {
    /**
     * The base asset identifier.
     * @type {string}
     * @memberof OptionsOptionExchangeGroup
     */
    asset_id_base?: string | null;
    /**
     * The quote asset identifier.
     * @type {string}
     * @memberof OptionsOptionExchangeGroup
     */
    asset_id_quote?: string | null;
    /**
     * The underlying price of the option.
     * @type {number}
     * @memberof OptionsOptionExchangeGroup
     */
    underlying_price?: number | null;
    /**
     * The expiration time of the option.
     * @type {string}
     * @memberof OptionsOptionExchangeGroup
     */
    time_expiration?: string;
    /**
     * The list of strikes available.
     * @type {Array<OptionsStrike>}
     * @memberof OptionsOptionExchangeGroup
     */
    strikes?: Array<OptionsStrike> | null;
}
