// tslint:disable
/**
 * CoinAPI Market Data REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a listing item.
 * @export
 * @interface V1ListingItem
 */
export interface V1ListingItem {
    /**
     * Gets or sets the metric ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    metric_id?: string | null;
    /**
     * Gets or sets the symbol ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    symbol_id?: string | null;
    /**
     * Gets or sets the symbol ID from the exchange.
     * @type {string}
     * @memberof V1ListingItem
     */
    symbol_id_external?: string | null;
    /**
     * Gets or sets the exchange ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    exchange_id?: string | null;
    /**
     * Gets or sets the asset ID.
     * @type {string}
     * @memberof V1ListingItem
     */
    asset_id?: string | null;
    /**
     * Gets or sets the asset ID from the exchange.
     * @type {string}
     * @memberof V1ListingItem
     */
    asset_id_external?: string | null;
    /**
     * Gets or sets the chain id.
     * @type {string}
     * @memberof V1ListingItem
     */
    chain_id?: string | null;
    /**
     * Gets or sets the network id.
     * @type {string}
     * @memberof V1ListingItem
     */
    network_id?: string | null;
}
