/**
 * REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents a metric information.
*/
export class V1MetricInfo {
    /**
    * Gets or sets the metric identifier.
    */
    'metricId'?: string | null;
    /**
    * Gets or sets the description of the metric.
    */
    'description'?: string | null;
    /**
    * Gets or sets the source identifier of the metric.
    */
    'sourceId'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "metricId",
            "baseName": "metric_id",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "sourceId",
            "baseName": "source_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1MetricInfo.attributeTypeMap;
    }
}

