note
 description:"[
		REST API
 		No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  		The version of the OpenAPI document: v1
 	    Contact: support@apibricks.io

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class FIN_FEED_API_EXCHANGE_MODEL

inherit


  STRING_TABLE [ANY]

feature --Access

    exchange_id: detachable STRING_32
      
    last_datapoint_date: detachable STRING_32
      
    mic: detachable STRING_32
      
    operating_mic: detachable STRING_32
      
    oprt_sgmt: detachable STRING_32
      
    market_name_institution_description: detachable STRING_32
      
    legal_entity_name: detachable STRING_32
      
    lei: detachable STRING_32
      
    market_category_code: detachable STRING_32
      
    acronym: detachable STRING_32
      
    iso_country_code: detachable STRING_32
      
    city: detachable STRING_32
      
    website: detachable STRING_32
      
    status: detachable STRING_32
      
    creation_date: detachable DATE_TIME
      
    last_update_date: detachable DATE_TIME
      
    last_validation_date: detachable DATE_TIME
      
    expiry_date: detachable DATE_TIME
      
    comments: detachable STRING_32
      

feature -- Change Element

    set_exchange_id (a_name: like exchange_id)
        -- Set 'exchange_id' with 'a_name'.
      do
        exchange_id := a_name
      ensure
        exchange_id_set: exchange_id = a_name
      end

    set_last_datapoint_date (a_name: like last_datapoint_date)
        -- Set 'last_datapoint_date' with 'a_name'.
      do
        last_datapoint_date := a_name
      ensure
        last_datapoint_date_set: last_datapoint_date = a_name
      end

    set_mic (a_name: like mic)
        -- Set 'mic' with 'a_name'.
      do
        mic := a_name
      ensure
        mic_set: mic = a_name
      end

    set_operating_mic (a_name: like operating_mic)
        -- Set 'operating_mic' with 'a_name'.
      do
        operating_mic := a_name
      ensure
        operating_mic_set: operating_mic = a_name
      end

    set_oprt_sgmt (a_name: like oprt_sgmt)
        -- Set 'oprt_sgmt' with 'a_name'.
      do
        oprt_sgmt := a_name
      ensure
        oprt_sgmt_set: oprt_sgmt = a_name
      end

    set_market_name_institution_description (a_name: like market_name_institution_description)
        -- Set 'market_name_institution_description' with 'a_name'.
      do
        market_name_institution_description := a_name
      ensure
        market_name_institution_description_set: market_name_institution_description = a_name
      end

    set_legal_entity_name (a_name: like legal_entity_name)
        -- Set 'legal_entity_name' with 'a_name'.
      do
        legal_entity_name := a_name
      ensure
        legal_entity_name_set: legal_entity_name = a_name
      end

    set_lei (a_name: like lei)
        -- Set 'lei' with 'a_name'.
      do
        lei := a_name
      ensure
        lei_set: lei = a_name
      end

    set_market_category_code (a_name: like market_category_code)
        -- Set 'market_category_code' with 'a_name'.
      do
        market_category_code := a_name
      ensure
        market_category_code_set: market_category_code = a_name
      end

    set_acronym (a_name: like acronym)
        -- Set 'acronym' with 'a_name'.
      do
        acronym := a_name
      ensure
        acronym_set: acronym = a_name
      end

    set_iso_country_code (a_name: like iso_country_code)
        -- Set 'iso_country_code' with 'a_name'.
      do
        iso_country_code := a_name
      ensure
        iso_country_code_set: iso_country_code = a_name
      end

    set_city (a_name: like city)
        -- Set 'city' with 'a_name'.
      do
        city := a_name
      ensure
        city_set: city = a_name
      end

    set_website (a_name: like website)
        -- Set 'website' with 'a_name'.
      do
        website := a_name
      ensure
        website_set: website = a_name
      end

    set_status (a_name: like status)
        -- Set 'status' with 'a_name'.
      do
        status := a_name
      ensure
        status_set: status = a_name
      end

    set_creation_date (a_name: like creation_date)
        -- Set 'creation_date' with 'a_name'.
      do
        creation_date := a_name
      ensure
        creation_date_set: creation_date = a_name
      end

    set_last_update_date (a_name: like last_update_date)
        -- Set 'last_update_date' with 'a_name'.
      do
        last_update_date := a_name
      ensure
        last_update_date_set: last_update_date = a_name
      end

    set_last_validation_date (a_name: like last_validation_date)
        -- Set 'last_validation_date' with 'a_name'.
      do
        last_validation_date := a_name
      ensure
        last_validation_date_set: last_validation_date = a_name
      end

    set_expiry_date (a_name: like expiry_date)
        -- Set 'expiry_date' with 'a_name'.
      do
        expiry_date := a_name
      ensure
        expiry_date_set: expiry_date = a_name
      end

    set_comments (a_name: like comments)
        -- Set 'comments' with 'a_name'.
      do
        comments := a_name
      ensure
        comments_set: comments = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append(out_)
        Result.append("%Nclass FIN_FEED_API_EXCHANGE_MODEL%N")
        if attached exchange_id as l_exchange_id then
          Result.append ("%Nexchange_id:")
          Result.append (l_exchange_id.out)
          Result.append ("%N")
        end
        if attached last_datapoint_date as l_last_datapoint_date then
          Result.append ("%Nlast_datapoint_date:")
          Result.append (l_last_datapoint_date.out)
          Result.append ("%N")
        end
        if attached mic as l_mic then
          Result.append ("%Nmic:")
          Result.append (l_mic.out)
          Result.append ("%N")
        end
        if attached operating_mic as l_operating_mic then
          Result.append ("%Noperating_mic:")
          Result.append (l_operating_mic.out)
          Result.append ("%N")
        end
        if attached oprt_sgmt as l_oprt_sgmt then
          Result.append ("%Noprt_sgmt:")
          Result.append (l_oprt_sgmt.out)
          Result.append ("%N")
        end
        if attached market_name_institution_description as l_market_name_institution_description then
          Result.append ("%Nmarket_name_institution_description:")
          Result.append (l_market_name_institution_description.out)
          Result.append ("%N")
        end
        if attached legal_entity_name as l_legal_entity_name then
          Result.append ("%Nlegal_entity_name:")
          Result.append (l_legal_entity_name.out)
          Result.append ("%N")
        end
        if attached lei as l_lei then
          Result.append ("%Nlei:")
          Result.append (l_lei.out)
          Result.append ("%N")
        end
        if attached market_category_code as l_market_category_code then
          Result.append ("%Nmarket_category_code:")
          Result.append (l_market_category_code.out)
          Result.append ("%N")
        end
        if attached acronym as l_acronym then
          Result.append ("%Nacronym:")
          Result.append (l_acronym.out)
          Result.append ("%N")
        end
        if attached iso_country_code as l_iso_country_code then
          Result.append ("%Niso_country_code:")
          Result.append (l_iso_country_code.out)
          Result.append ("%N")
        end
        if attached city as l_city then
          Result.append ("%Ncity:")
          Result.append (l_city.out)
          Result.append ("%N")
        end
        if attached website as l_website then
          Result.append ("%Nwebsite:")
          Result.append (l_website.out)
          Result.append ("%N")
        end
        if attached status as l_status then
          Result.append ("%Nstatus:")
          Result.append (l_status.out)
          Result.append ("%N")
        end
        if attached creation_date as l_creation_date then
          Result.append ("%Ncreation_date:")
          Result.append (l_creation_date.out)
          Result.append ("%N")
        end
        if attached last_update_date as l_last_update_date then
          Result.append ("%Nlast_update_date:")
          Result.append (l_last_update_date.out)
          Result.append ("%N")
        end
        if attached last_validation_date as l_last_validation_date then
          Result.append ("%Nlast_validation_date:")
          Result.append (l_last_validation_date.out)
          Result.append ("%N")
        end
        if attached expiry_date as l_expiry_date then
          Result.append ("%Nexpiry_date:")
          Result.append (l_expiry_date.out)
          Result.append ("%N")
        end
        if attached comments as l_comments then
          Result.append ("%Ncomments:")
          Result.append (l_comments.out)
          Result.append ("%N")
        end
      end
end

