#
# CoinAPI Market Data REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Contact: support@apibricks.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'V1GeneralData' {
    Context 'V1GeneralData' {
        It 'Initialize-V1GeneralData' {
            # a simple test to create an object
            #$NewObject = Initialize-V1GeneralData -EntryTime "TEST_VALUE" -RecvTime "TEST_VALUE" -ExchangeId "TEST_VALUE" -AssetId "TEST_VALUE" -SymbolId "TEST_VALUE" -MetricId "TEST_VALUE" -ValueDecimal "TEST_VALUE" -ValueText "TEST_VALUE" -ValueTime "TEST_VALUE"
            #$NewObject | Should -BeOfType V1GeneralData
            #$NewObject.property | Should -Be 0
        }
    }
}
