# flake8: noqa

# import apis into api package
from api_bricks_coinapi_market_data_api_rest.api.exchange_rates_api import ExchangeRatesApi
from api_bricks_coinapi_market_data_api_rest.api.metadata_api import MetadataApi
from api_bricks_coinapi_market_data_api_rest.api.metrics_v1_api import MetricsV1Api
from api_bricks_coinapi_market_data_api_rest.api.metrics_v2_api import MetricsV2Api
from api_bricks_coinapi_market_data_api_rest.api.ohlcv_api import OhlcvApi
from api_bricks_coinapi_market_data_api_rest.api.options_api import OptionsApi
from api_bricks_coinapi_market_data_api_rest.api.order_book_api import OrderBookApi
from api_bricks_coinapi_market_data_api_rest.api.order_book_l3_api import OrderBookL3Api
from api_bricks_coinapi_market_data_api_rest.api.quotes_api import QuotesApi
from api_bricks_coinapi_market_data_api_rest.api.trades_api import TradesApi

