/**
 * Exchange Rates Historical REST API
 *
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents an icon.
 */
export interface V1Icon { 
    /**
     * Gets or sets the exchange ID associated with the icon.
     */
    exchange_id?: string | null;
    /**
     * Gets or sets the asset ID associated with the icon.
     */
    asset_id?: string | null;
    /**
     * Gets or sets the URL of the icon.
     */
    url?: string | null;
}

