# coding: utf-8

"""
    CoinAPI Indexes REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_bricks_coinapi_indexes_api_rest.api.periods_api import PeriodsApi


class TestPeriodsApi(unittest.TestCase):
    """PeriodsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PeriodsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_metadata_periods_get(self) -> None:
        """Test case for v1_metadata_periods_get

        List all periods
        """
        pass


if __name__ == '__main__':
    unittest.main()
