/**
 * FinFeedAPI Stock REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Represents the response DTO for quote update information
 **/
@ApiModel(description = "Represents the response DTO for quote update information")
public class Level1QuoteUpdateModel {
  
  @SerializedName("symbol")
  private String symbol = null;
  @SerializedName("timestamp_nanos")
  private Long timestampNanos = null;
  @SerializedName("timestamp")
  private Date timestamp = null;
  @SerializedName("is_symbol_available")
  private Boolean isSymbolAvailable = null;
  @SerializedName("is_pre_post_market_session")
  private Boolean isPrePostMarketSession = null;
  @SerializedName("ask_size")
  private Integer askSize = null;
  @SerializedName("ask_price")
  private Double askPrice = null;
  @SerializedName("bid_price")
  private Double bidPrice = null;
  @SerializedName("bid_size")
  private Integer bidSize = null;

  /**
   * The stock symbol
   **/
  @ApiModelProperty(value = "The stock symbol")
  public String getSymbol() {
    return symbol;
  }
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  /**
   * Original timestamp in nanoseconds since epoch
   **/
  @ApiModelProperty(value = "Original timestamp in nanoseconds since epoch")
  public Long getTimestampNanos() {
    return timestampNanos;
  }
  public void setTimestampNanos(Long timestampNanos) {
    this.timestampNanos = timestampNanos;
  }

  /**
   * Time when the quote update was recorded as DateTime
   **/
  @ApiModelProperty(value = "Time when the quote update was recorded as DateTime")
  public Date getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Gets whether the symbol is available for trading True if active, False if halted, paused, or otherwise not available
   **/
  @ApiModelProperty(value = "Gets whether the symbol is available for trading True if active, False if halted, paused, or otherwise not available")
  public Boolean getIsSymbolAvailable() {
    return isSymbolAvailable;
  }
  public void setIsSymbolAvailable(Boolean isSymbolAvailable) {
    this.isSymbolAvailable = isSymbolAvailable;
  }

  /**
   * Gets whether the market session is regular or pre/post-market True if pre/post-market session, False if regular market session
   **/
  @ApiModelProperty(value = "Gets whether the market session is regular or pre/post-market True if pre/post-market session, False if regular market session")
  public Boolean getIsPrePostMarketSession() {
    return isPrePostMarketSession;
  }
  public void setIsPrePostMarketSession(Boolean isPrePostMarketSession) {
    this.isPrePostMarketSession = isPrePostMarketSession;
  }

  /**
   * Ask size in number of shares
   **/
  @ApiModelProperty(value = "Ask size in number of shares")
  public Integer getAskSize() {
    return askSize;
  }
  public void setAskSize(Integer askSize) {
    this.askSize = askSize;
  }

  /**
   * Ask price as decimal
   **/
  @ApiModelProperty(value = "Ask price as decimal")
  public Double getAskPrice() {
    return askPrice;
  }
  public void setAskPrice(Double askPrice) {
    this.askPrice = askPrice;
  }

  /**
   * Bid price as decimal
   **/
  @ApiModelProperty(value = "Bid price as decimal")
  public Double getBidPrice() {
    return bidPrice;
  }
  public void setBidPrice(Double bidPrice) {
    this.bidPrice = bidPrice;
  }

  /**
   * Bid size in number of shares
   **/
  @ApiModelProperty(value = "Bid size in number of shares")
  public Integer getBidSize() {
    return bidSize;
  }
  public void setBidSize(Integer bidSize) {
    this.bidSize = bidSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Level1QuoteUpdateModel level1QuoteUpdateModel = (Level1QuoteUpdateModel) o;
    return (this.symbol == null ? level1QuoteUpdateModel.symbol == null : this.symbol.equals(level1QuoteUpdateModel.symbol)) &&
        (this.timestampNanos == null ? level1QuoteUpdateModel.timestampNanos == null : this.timestampNanos.equals(level1QuoteUpdateModel.timestampNanos)) &&
        (this.timestamp == null ? level1QuoteUpdateModel.timestamp == null : this.timestamp.equals(level1QuoteUpdateModel.timestamp)) &&
        (this.isSymbolAvailable == null ? level1QuoteUpdateModel.isSymbolAvailable == null : this.isSymbolAvailable.equals(level1QuoteUpdateModel.isSymbolAvailable)) &&
        (this.isPrePostMarketSession == null ? level1QuoteUpdateModel.isPrePostMarketSession == null : this.isPrePostMarketSession.equals(level1QuoteUpdateModel.isPrePostMarketSession)) &&
        (this.askSize == null ? level1QuoteUpdateModel.askSize == null : this.askSize.equals(level1QuoteUpdateModel.askSize)) &&
        (this.askPrice == null ? level1QuoteUpdateModel.askPrice == null : this.askPrice.equals(level1QuoteUpdateModel.askPrice)) &&
        (this.bidPrice == null ? level1QuoteUpdateModel.bidPrice == null : this.bidPrice.equals(level1QuoteUpdateModel.bidPrice)) &&
        (this.bidSize == null ? level1QuoteUpdateModel.bidSize == null : this.bidSize.equals(level1QuoteUpdateModel.bidSize));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.symbol == null ? 0: this.symbol.hashCode());
    result = 31 * result + (this.timestampNanos == null ? 0: this.timestampNanos.hashCode());
    result = 31 * result + (this.timestamp == null ? 0: this.timestamp.hashCode());
    result = 31 * result + (this.isSymbolAvailable == null ? 0: this.isSymbolAvailable.hashCode());
    result = 31 * result + (this.isPrePostMarketSession == null ? 0: this.isPrePostMarketSession.hashCode());
    result = 31 * result + (this.askSize == null ? 0: this.askSize.hashCode());
    result = 31 * result + (this.askPrice == null ? 0: this.askPrice.hashCode());
    result = 31 * result + (this.bidPrice == null ? 0: this.bidPrice.hashCode());
    result = 31 * result + (this.bidSize == null ? 0: this.bidSize.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Level1QuoteUpdateModel {\n");
    
    sb.append("  symbol: ").append(symbol).append("\n");
    sb.append("  timestampNanos: ").append(timestampNanos).append("\n");
    sb.append("  timestamp: ").append(timestamp).append("\n");
    sb.append("  isSymbolAvailable: ").append(isSymbolAvailable).append("\n");
    sb.append("  isPrePostMarketSession: ").append(isPrePostMarketSession).append("\n");
    sb.append("  askSize: ").append(askSize).append("\n");
    sb.append("  askPrice: ").append(askPrice).append("\n");
    sb.append("  bidPrice: ").append(bidPrice).append("\n");
    sb.append("  bidSize: ").append(bidSize).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
