/*
 * CoinAPI Market Data REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using APIBricks.CoinAPI.MarketDataAPI.REST.V1.Model;
using APIBricks.CoinAPI.MarketDataAPI.REST.V1.Client;
using System.Reflection;

namespace APIBricks.CoinAPI.MarketDataAPI.REST.V1.Test.Model
{
    /// <summary>
    ///  Class for testing V1ExchangeRatesTimeseriesItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1ExchangeRatesTimeseriesItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1ExchangeRatesTimeseriesItem
        //private V1ExchangeRatesTimeseriesItem instance;

        public V1ExchangeRatesTimeseriesItemTests()
        {
            // TODO uncomment below to create an instance of V1ExchangeRatesTimeseriesItem
            //instance = new V1ExchangeRatesTimeseriesItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1ExchangeRatesTimeseriesItem
        /// </summary>
        [Fact]
        public void V1ExchangeRatesTimeseriesItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1ExchangeRatesTimeseriesItem
            //Assert.IsType<V1ExchangeRatesTimeseriesItem>(instance);
        }

        /// <summary>
        /// Test the property 'TimePeriodStart'
        /// </summary>
        [Fact]
        public void TimePeriodStartTest()
        {
            // TODO unit test for the property 'TimePeriodStart'
        }

        /// <summary>
        /// Test the property 'TimePeriodEnd'
        /// </summary>
        [Fact]
        public void TimePeriodEndTest()
        {
            // TODO unit test for the property 'TimePeriodEnd'
        }

        /// <summary>
        /// Test the property 'TimeOpen'
        /// </summary>
        [Fact]
        public void TimeOpenTest()
        {
            // TODO unit test for the property 'TimeOpen'
        }

        /// <summary>
        /// Test the property 'TimeClose'
        /// </summary>
        [Fact]
        public void TimeCloseTest()
        {
            // TODO unit test for the property 'TimeClose'
        }

        /// <summary>
        /// Test the property 'RateOpen'
        /// </summary>
        [Fact]
        public void RateOpenTest()
        {
            // TODO unit test for the property 'RateOpen'
        }

        /// <summary>
        /// Test the property 'RateHigh'
        /// </summary>
        [Fact]
        public void RateHighTest()
        {
            // TODO unit test for the property 'RateHigh'
        }

        /// <summary>
        /// Test the property 'RateLow'
        /// </summary>
        [Fact]
        public void RateLowTest()
        {
            // TODO unit test for the property 'RateLow'
        }

        /// <summary>
        /// Test the property 'RateClose'
        /// </summary>
        [Fact]
        public void RateCloseTest()
        {
            // TODO unit test for the property 'RateClose'
        }
    }
}
