# coding: utf-8

"""
    CoinAPI Market Data REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: support@apibricks.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_bricks_coinapi_market_data_api_rest.models.v1_quote import V1Quote

class TestV1Quote(unittest.TestCase):
    """V1Quote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1Quote:
        """Test V1Quote
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1Quote`
        """
        model = V1Quote()
        if include_optional:
            return V1Quote(
                symbol_id = '',
                time_exchange = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                time_coinapi = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ask_price = 1.337,
                ask_size = 1.337,
                bid_price = 1.337,
                bid_size = 1.337
            )
        else:
            return V1Quote(
        )
        """

    def testV1Quote(self):
        """Test V1Quote"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
