#
# REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Contact: support@apibricks.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Level3DeleteOrderModel' {
    Context 'Level3DeleteOrderModel' {
        It 'Initialize-Level3DeleteOrderModel' {
            # a simple test to create an object
            #$NewObject = Initialize-Level3DeleteOrderModel -Symbol "TEST_VALUE" -TimestampNanos "TEST_VALUE" -Timestamp "TEST_VALUE" -OrderIdReference "TEST_VALUE"
            #$NewObject | Should -BeOfType Level3DeleteOrderModel
            #$NewObject.property | Should -Be 0
        }
    }
}
