/*
 * Indexes REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IndexesIndexTimeseriesItem
 */
public class IndexesIndexTimeseriesItemTest {
    private final IndexesIndexTimeseriesItem model = new IndexesIndexTimeseriesItem();

    /**
     * Model tests for IndexesIndexTimeseriesItem
     */
    @Test
    public void testIndexesIndexTimeseriesItem() {
        // TODO: test IndexesIndexTimeseriesItem
    }

    /**
     * Test the property 'timePeriodStart'
     */
    @Test
    public void timePeriodStartTest() {
        // TODO: test timePeriodStart
    }

    /**
     * Test the property 'timePeriodEnd'
     */
    @Test
    public void timePeriodEndTest() {
        // TODO: test timePeriodEnd
    }

    /**
     * Test the property 'timeOpen'
     */
    @Test
    public void timeOpenTest() {
        // TODO: test timeOpen
    }

    /**
     * Test the property 'timeClose'
     */
    @Test
    public void timeCloseTest() {
        // TODO: test timeClose
    }

    /**
     * Test the property 'valueOpen'
     */
    @Test
    public void valueOpenTest() {
        // TODO: test valueOpen
    }

    /**
     * Test the property 'valueHigh'
     */
    @Test
    public void valueHighTest() {
        // TODO: test valueHigh
    }

    /**
     * Test the property 'valueLow'
     */
    @Test
    public void valueLowTest() {
        // TODO: test valueLow
    }

    /**
     * Test the property 'valueClose'
     */
    @Test
    public void valueCloseTest() {
        // TODO: test valueClose
    }

    /**
     * Test the property 'valueCount'
     */
    @Test
    public void valueCountTest() {
        // TODO: test valueCount
    }

}
