/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents the response DTO for trading status information
 *
 * @param symbol The stock symbol
 * @param timestampNanos Original timestamp in nanoseconds since epoch
 * @param timestamp Time when the trading status was recorded as DateTime
 * @param isTradingLive Gets whether the security is currently trading on IEX
 * @param isTradingHalted Gets whether the security is halted across all US equity markets
 * @param isTradingInOrderAcceptancePeriod Gets whether the security is in Order Acceptance Period on IEX
 * @param isTradingPaused Gets whether the security is paused and in Order Acceptance Period on IEX
 * @param isReasonHaltNewsPending Gets whether the halt reason is News Pending
 * @param isReasonIpoNotYetTrading Gets whether the halt reason is IPO Not Yet Trading
 * @param isReasonIpoDeferred Gets whether the halt reason is IPO Deferred
 * @param isReasonHaltNewsDissemination Gets whether the order acceptance period reason is Halt News Dissemination
 * @param isReasonIpoOrderAcceptancePeriod Gets whether the order acceptance period reason is IPO Order Acceptance Period
 * @param isReasonIpoPreLaunchPeriod Gets whether the order acceptance period reason is IPO Pre-Launch Period
 * @param isReasonMarketWideCircuitBreakerLevel1 Gets whether the order acceptance period reason is Market-Wide Circuit Breaker Level 1 – Breached
 * @param isReasonMarketWideCircuitBreakerLevel2 Gets whether the order acceptance period reason is Market-Wide Circuit Breaker Level 2 – Breached
 * @param isReasonMarketWideCircuitBreakerLevel3 Gets whether the halt reason is Market-Wide Circuit Breaker Level 3 – Breached
 * @param isReasonNotApplicable Gets whether the reason is Not Applicable
 * @param isReasonNotAvailable Gets whether the halt reason is Not Available
 */


data class AdminTradingStatusModel (

    /* The stock symbol */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Original timestamp in nanoseconds since epoch */
    @Json(name = "timestamp_nanos")
    val timestampNanos: kotlin.Long? = null,

    /* Time when the trading status was recorded as DateTime */
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    /* Gets whether the security is currently trading on IEX */
    @Json(name = "is_trading_live")
    val isTradingLive: kotlin.Boolean? = null,

    /* Gets whether the security is halted across all US equity markets */
    @Json(name = "is_trading_halted")
    val isTradingHalted: kotlin.Boolean? = null,

    /* Gets whether the security is in Order Acceptance Period on IEX */
    @Json(name = "is_trading_in_order_acceptance_period")
    val isTradingInOrderAcceptancePeriod: kotlin.Boolean? = null,

    /* Gets whether the security is paused and in Order Acceptance Period on IEX */
    @Json(name = "is_trading_paused")
    val isTradingPaused: kotlin.Boolean? = null,

    /* Gets whether the halt reason is News Pending */
    @Json(name = "is_reason_halt_news_pending")
    val isReasonHaltNewsPending: kotlin.Boolean? = null,

    /* Gets whether the halt reason is IPO Not Yet Trading */
    @Json(name = "is_reason_ipo_not_yet_trading")
    val isReasonIpoNotYetTrading: kotlin.Boolean? = null,

    /* Gets whether the halt reason is IPO Deferred */
    @Json(name = "is_reason_ipo_deferred")
    val isReasonIpoDeferred: kotlin.Boolean? = null,

    /* Gets whether the order acceptance period reason is Halt News Dissemination */
    @Json(name = "is_reason_halt_news_dissemination")
    val isReasonHaltNewsDissemination: kotlin.Boolean? = null,

    /* Gets whether the order acceptance period reason is IPO Order Acceptance Period */
    @Json(name = "is_reason_ipo_order_acceptance_period")
    val isReasonIpoOrderAcceptancePeriod: kotlin.Boolean? = null,

    /* Gets whether the order acceptance period reason is IPO Pre-Launch Period */
    @Json(name = "is_reason_ipo_pre_launch_period")
    val isReasonIpoPreLaunchPeriod: kotlin.Boolean? = null,

    /* Gets whether the order acceptance period reason is Market-Wide Circuit Breaker Level 1 – Breached */
    @Json(name = "is_reason_market_wide_circuit_breaker_level1")
    val isReasonMarketWideCircuitBreakerLevel1: kotlin.Boolean? = null,

    /* Gets whether the order acceptance period reason is Market-Wide Circuit Breaker Level 2 – Breached */
    @Json(name = "is_reason_market_wide_circuit_breaker_level2")
    val isReasonMarketWideCircuitBreakerLevel2: kotlin.Boolean? = null,

    /* Gets whether the halt reason is Market-Wide Circuit Breaker Level 3 – Breached */
    @Json(name = "is_reason_market_wide_circuit_breaker_level3")
    val isReasonMarketWideCircuitBreakerLevel3: kotlin.Boolean? = null,

    /* Gets whether the reason is Not Applicable */
    @Json(name = "is_reason_not_applicable")
    val isReasonNotApplicable: kotlin.Boolean? = null,

    /* Gets whether the halt reason is Not Available */
    @Json(name = "is_reason_not_available")
    val isReasonNotAvailable: kotlin.Boolean? = null

) {


}

