/**
 * FinFeedAPI Stock REST API
 *
 * Contact: support@apibricks.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the response DTO for price level update information
 */
export interface Level2PriceLevelUpdateModel { 
    /**
     * The stock symbol
     */
    symbol?: string | null;
    /**
     * Original timestamp in nanoseconds since epoch
     */
    timestamp_nanos?: number;
    /**
     * Time when the price level update was recorded as DateTime
     */
    timestamp?: string;
    /**
     * Indicates if this is a price level update for the Buy Side.
     */
    is_side_buy?: boolean;
    /**
     * Indicates if event processing is complete.
     */
    is_event_processing_complete?: boolean;
    /**
     * Aggregate quoted size at the price level
     */
    size?: number;
    /**
     * Price level as decimal
     */
    price?: number;
}

