export * from './exchangeRates.service';
import { ExchangeRatesService } from './exchangeRates.service';
export * from './metadata.service';
import { MetadataService } from './metadata.service';
export * from './metricsV1.service';
import { MetricsV1Service } from './metricsV1.service';
export * from './metricsV2.service';
import { MetricsV2Service } from './metricsV2.service';
export * from './ohlcv.service';
import { OhlcvService } from './ohlcv.service';
export * from './options.service';
import { OptionsService } from './options.service';
export * from './orderBook.service';
import { OrderBookService } from './orderBook.service';
export * from './orderBookL3.service';
import { OrderBookL3Service } from './orderBookL3.service';
export * from './quotes.service';
import { QuotesService } from './quotes.service';
export * from './trades.service';
import { TradesService } from './trades.service';
export const APIS = [ExchangeRatesService, MetadataService, MetricsV1Service, MetricsV2Service, OhlcvService, OptionsService, OrderBookService, OrderBookL3Service, QuotesService, TradesService];
