export * from './ContentExtractionApi';
import { ContentExtractionApi } from './ContentExtractionApi';
export * from './FileDownloadApi';
import { FileDownloadApi } from './FileDownloadApi';
export * from './FilingMetadataApi';
import { FilingMetadataApi } from './FilingMetadataApi';
export * from './FullTextSearchApi';
import { FullTextSearchApi } from './FullTextSearchApi';
export * from './XBRLConversionApi';
import { XBRLConversionApi } from './XBRLConversionApi';
export const APIS = [ContentExtractionApi, FileDownloadApi, FilingMetadataApi, FullTextSearchApi, XBRLConversionApi];
