/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a quote data model.
 *
 * @param symbolId The symbol identifier.
 * @param timeExchange The exchange time of the quote.
 * @param timeCoinapi The CoinAPI time when the quote was received.
 * @param askPrice The best asking price.
 * @param askSize The volume resting on the best ask. If the value is equal to zero, then the size is unknown.
 * @param bidPrice The best bidding price.
 * @param bidSize The volume resting on the best bid. If the value is equal to zero, then the size is unknown.
 */


data class V1Quote (

    /* The symbol identifier. */
    @Json(name = "symbol_id")
    val symbolId: kotlin.String? = null,

    /* The exchange time of the quote. */
    @Json(name = "time_exchange")
    val timeExchange: java.time.OffsetDateTime? = null,

    /* The CoinAPI time when the quote was received. */
    @Json(name = "time_coinapi")
    val timeCoinapi: java.time.OffsetDateTime? = null,

    /* The best asking price. */
    @Json(name = "ask_price")
    val askPrice: kotlin.Double? = null,

    /* The volume resting on the best ask. If the value is equal to zero, then the size is unknown. */
    @Json(name = "ask_size")
    val askSize: kotlin.Double? = null,

    /* The best bidding price. */
    @Json(name = "bid_price")
    val bidPrice: kotlin.Double? = null,

    /* The volume resting on the best bid. If the value is equal to zero, then the size is unknown. */
    @Json(name = "bid_size")
    val bidSize: kotlin.Double? = null

) {


}

