--[[
  REST API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.admin_short_sale_price_test_status_model
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("admin_short_sale_price_test_status_model", function()
  local openapiclient_admin_short_sale_price_test_status_model = require "openapiclient.model.admin_short_sale_price_test_status_model"

  -- unit tests for the property 'symbol'
  describe("property symbol test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'timestamp_nanos'
  describe("property timestamp_nanos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'timestamp'
  describe("property timestamp test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'short_sale_price_test_status'
  describe("property short_sale_price_test_status test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'short_sale_price_test_status_code'
  describe("property short_sale_price_test_status_code test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'short_sale_price_test_status_text'
  describe("property short_sale_price_test_status_text test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'is_short_sale_price_test_not_in_effect'
  describe("property is_short_sale_price_test_not_in_effect test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'is_short_sale_price_test_in_effect'
  describe("property is_short_sale_price_test_in_effect test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'detail'
  describe("property detail test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'detail_code'
  describe("property detail_code test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'detail_text'
  describe("property detail_text test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'is_detail_no_price_test'
  describe("property is_detail_no_price_test test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'is_detail_activated'
  describe("property is_detail_activated test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'is_detail_continued'
  describe("property is_detail_continued test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'is_detail_deactivated'
  describe("property is_detail_deactivated test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'is_detail_not_available'
  describe("property is_detail_not_available test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
