#
# Indexes REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v1
# Contact: support@apibricks.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'IndexesIndexDefinitionSnapshotEntry' {
    Context 'IndexesIndexDefinitionSnapshotEntry' {
        It 'Initialize-IndexesIndexDefinitionSnapshotEntry' {
            # a simple test to create an object
            #$NewObject = Initialize-IndexesIndexDefinitionSnapshotEntry -IndexId "TEST_VALUE" -Timestamp "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType IndexesIndexDefinitionSnapshotEntry
            #$NewObject.property | Should -Be 0
        }
    }
}
