=begin comment

REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@apibricks.io
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::NativeIEXApi');

my $api = WWW::OpenAPIClient::NativeIEXApi->new();
isa_ok($api, 'WWW::OpenAPIClient::NativeIEXApi');

#
# v1_native_iex_admin_messages_symbol_get test
#
# uncomment below and update the test
#my $v1_native_iex_admin_messages_symbol_get_symbol = undef; # replace NULL with a proper value
#my $v1_native_iex_admin_messages_symbol_get_date = undef; # replace NULL with a proper value
#my $v1_native_iex_admin_messages_symbol_get_result = $api->v1_native_iex_admin_messages_symbol_get(symbol => $v1_native_iex_admin_messages_symbol_get_symbol, date => $v1_native_iex_admin_messages_symbol_get_date);

#
# v1_native_iex_admin_system_event_get test
#
# uncomment below and update the test
#my $v1_native_iex_admin_system_event_get_date = undef; # replace NULL with a proper value
#my $v1_native_iex_admin_system_event_get_result = $api->v1_native_iex_admin_system_event_get(date => $v1_native_iex_admin_system_event_get_date);

#
# v1_native_iex_level1_quote_symbol_get test
#
# uncomment below and update the test
#my $v1_native_iex_level1_quote_symbol_get_symbol = undef; # replace NULL with a proper value
#my $v1_native_iex_level1_quote_symbol_get_date = undef; # replace NULL with a proper value
#my $v1_native_iex_level1_quote_symbol_get_result = $api->v1_native_iex_level1_quote_symbol_get(symbol => $v1_native_iex_level1_quote_symbol_get_symbol, date => $v1_native_iex_level1_quote_symbol_get_date);

#
# v1_native_iex_level2_price_level_update_symbol_get test
#
# uncomment below and update the test
#my $v1_native_iex_level2_price_level_update_symbol_get_symbol = undef; # replace NULL with a proper value
#my $v1_native_iex_level2_price_level_update_symbol_get_date = undef; # replace NULL with a proper value
#my $v1_native_iex_level2_price_level_update_symbol_get_result = $api->v1_native_iex_level2_price_level_update_symbol_get(symbol => $v1_native_iex_level2_price_level_update_symbol_get_symbol, date => $v1_native_iex_level2_price_level_update_symbol_get_date);

#
# v1_native_iex_level3_order_book_symbol_get test
#
# uncomment below and update the test
#my $v1_native_iex_level3_order_book_symbol_get_symbol = undef; # replace NULL with a proper value
#my $v1_native_iex_level3_order_book_symbol_get_date = undef; # replace NULL with a proper value
#my $v1_native_iex_level3_order_book_symbol_get_result = $api->v1_native_iex_level3_order_book_symbol_get(symbol => $v1_native_iex_level3_order_book_symbol_get_symbol, date => $v1_native_iex_level3_order_book_symbol_get_date);

#
# v1_native_iex_trade_symbol_get test
#
# uncomment below and update the test
#my $v1_native_iex_trade_symbol_get_symbol = undef; # replace NULL with a proper value
#my $v1_native_iex_trade_symbol_get_date = undef; # replace NULL with a proper value
#my $v1_native_iex_trade_symbol_get_result = $api->v1_native_iex_trade_symbol_get(symbol => $v1_native_iex_trade_symbol_get_symbol, date => $v1_native_iex_trade_symbol_get_date);


done_testing();
