# NOTE: This file is auto generated by OpenAPI Generator 7.13.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule RESTAPI.Model.Level2PriceLevelUpdateModel do
  @moduledoc """
  Represents the response DTO for price level update information
  """

  @derive JSON.Encoder
  defstruct [
    :symbol,
    :timestamp_nanos,
    :timestamp,
    :is_side_buy,
    :is_event_processing_complete,
    :size,
    :price
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :timestamp_nanos => integer() | nil,
    :timestamp => DateTime.t | nil,
    :is_side_buy => boolean() | nil,
    :is_event_processing_complete => boolean() | nil,
    :size => integer() | nil,
    :price => float() | nil
  }

  def decode(value) do
    value
  end
end

