# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrderBookApi")

api_instance <- OrderBookApi$new()

test_that("V1OrderbooksSymbolIdCurrentGet", {
  # tests for V1OrderbooksSymbolIdCurrentGet
  # base path: https://rest.coinapi.io
  # Get current order book
  # Retrieves the current order book for the specified symbol.
  # @param symbol_id character The symbol ID (from the Metadata -> Symbols)
  # @param limit_levels integer The maximum number of levels to include in the response. (optional)
  # @return [V1OrderBookBase]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1OrderbooksSymbolIdDepthCurrentGet", {
  # tests for V1OrderbooksSymbolIdDepthCurrentGet
  # base path: https://rest.coinapi.io
  # Current depth of the order book
  # Retrieves the current depth of the order book for the specified symbol.
  # @param symbol_id character The symbol ID (from the Metadata -> Symbols)
  # @param limit_levels integer The maximum number of levels to include in the response. (optional)
  # @return [V1OrderBookDepth]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1OrderbooksSymbolIdHistoryGet", {
  # tests for V1OrderbooksSymbolIdHistoryGet
  # base path: https://rest.coinapi.io
  # Historical data
  # Get historical order book snapshots for a specific symbol within time range, returned in time ascending order.                :::info  The historical order book data via the REST API is currently limited by a number of updates and to the maximum number of 20 levels.  :::    :::warning  The &#39;time_start&#39; and &#39;time_end&#39; parameters must be from the same day as this endpoint provides intraday data only for specific day.  Please use the &#39;date&#39; parameter instead for querying data for a specific day without filter.  :::
  # @param symbol_id character Symbol identifier for requested timeseries (from the Metadata -> Symbols)
  # @param date character Date in ISO 8601, returned data is for the whole given day (preferred method, required if 'time_start' is not provided) (optional)
  # @param time_start character Starting time in ISO 8601 (deprecated, use 'date' instead) (optional)
  # @param time_end character Timeseries ending time in ISO 8601 (deprecated, use 'date' instead) (optional)
  # @param limit integer Amount of items to return (optional, minimum is 1, maximum is 100000, default value is 100, if the parameter is used then every 100 output items are counted as one request) (optional)
  # @param limit_levels integer Maximum amount of levels from each side of the book to include in response (optional) (optional)
  # @return [array[V1OrderBook]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1OrderbooksSymbolIdLatestGet", {
  # tests for V1OrderbooksSymbolIdLatestGet
  # base path: https://rest.coinapi.io
  # Latest data
  # Get latest order book snapshots for a specific symbol, returned in time descending order.                :::info  The historical order book data via the REST API is currently limited by a number of updates and to the maximum number of 20 levels.  :::
  # @param symbol_id character Symbol identifier of requested timeseries (from the Metadata -> Symbols)
  # @param limit integer Amount of items to return (optional, mininum is 1, maximum is 100000, default value is 100, if the parameter is used then every 100 output items are counted as one request) (optional)
  # @param limit_levels integer Maximum amount of levels from each side of the book to include in response (optional) (optional)
  # @return [array[V1OrderBook]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
