# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AdminShortSalePriceTestStatusModel")

model_instance <- AdminShortSalePriceTestStatusModel$new()

test_that("symbol", {
  # tests for the property `symbol` (character)
  # The stock symbol

  # uncomment below to test the property
  #expect_equal(model.instance$`symbol`, "EXPECTED_RESULT")
})

test_that("timestamp_nanos", {
  # tests for the property `timestamp_nanos` (integer)
  # Original timestamp in nanoseconds since epoch

  # uncomment below to test the property
  #expect_equal(model.instance$`timestamp_nanos`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)
  # Time when the short sale price test status was recorded as DateTime

  # uncomment below to test the property
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("short_sale_price_test_status", {
  # tests for the property `short_sale_price_test_status` (integer)
  # Short sale price test status as byte value

  # uncomment below to test the property
  #expect_equal(model.instance$`short_sale_price_test_status`, "EXPECTED_RESULT")
})

test_that("short_sale_price_test_status_code", {
  # tests for the property `short_sale_price_test_status_code` (character)
  # Short sale price test status as hex string

  # uncomment below to test the property
  #expect_equal(model.instance$`short_sale_price_test_status_code`, "EXPECTED_RESULT")
})

test_that("short_sale_price_test_status_text", {
  # tests for the property `short_sale_price_test_status_text` (character)
  # Human-readable description of the short sale price test status

  # uncomment below to test the property
  #expect_equal(model.instance$`short_sale_price_test_status_text`, "EXPECTED_RESULT")
})

test_that("is_short_sale_price_test_not_in_effect", {
  # tests for the property `is_short_sale_price_test_not_in_effect` (character)
  # Indicates if the short sale price test is not in effect

  # uncomment below to test the property
  #expect_equal(model.instance$`is_short_sale_price_test_not_in_effect`, "EXPECTED_RESULT")
})

test_that("is_short_sale_price_test_in_effect", {
  # tests for the property `is_short_sale_price_test_in_effect` (character)
  # Indicates if the short sale price test is in effect

  # uncomment below to test the property
  #expect_equal(model.instance$`is_short_sale_price_test_in_effect`, "EXPECTED_RESULT")
})

test_that("detail", {
  # tests for the property `detail` (integer)
  # Detail of the short sale price test as byte value

  # uncomment below to test the property
  #expect_equal(model.instance$`detail`, "EXPECTED_RESULT")
})

test_that("detail_code", {
  # tests for the property `detail_code` (character)
  # Detail of the short sale price test as character string

  # uncomment below to test the property
  #expect_equal(model.instance$`detail_code`, "EXPECTED_RESULT")
})

test_that("detail_text", {
  # tests for the property `detail_text` (character)
  # Human-readable description of the short sale price test detail

  # uncomment below to test the property
  #expect_equal(model.instance$`detail_text`, "EXPECTED_RESULT")
})

test_that("is_detail_no_price_test", {
  # tests for the property `is_detail_no_price_test` (character)
  # Indicates if there is no price test in place

  # uncomment below to test the property
  #expect_equal(model.instance$`is_detail_no_price_test`, "EXPECTED_RESULT")
})

test_that("is_detail_activated", {
  # tests for the property `is_detail_activated` (character)
  # Indicates if the short sale price test restriction is in effect due to an intraday price drop

  # uncomment below to test the property
  #expect_equal(model.instance$`is_detail_activated`, "EXPECTED_RESULT")
})

test_that("is_detail_continued", {
  # tests for the property `is_detail_continued` (character)
  # Indicates if the short sale price test restriction remains in effect from prior day

  # uncomment below to test the property
  #expect_equal(model.instance$`is_detail_continued`, "EXPECTED_RESULT")
})

test_that("is_detail_deactivated", {
  # tests for the property `is_detail_deactivated` (character)
  # Indicates if the short sale price test restriction is deactivated

  # uncomment below to test the property
  #expect_equal(model.instance$`is_detail_deactivated`, "EXPECTED_RESULT")
})

test_that("is_detail_not_available", {
  # tests for the property `is_detail_not_available` (character)
  # Indicates if the detail is not available

  # uncomment below to test the property
  #expect_equal(model.instance$`is_detail_not_available`, "EXPECTED_RESULT")
})
