--[[
  Exchange Rates Historical REST API

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: v1
  Contact: support@apibricks.io
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.api.exchange_rates_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("exchange_rates_api", function()
  local openapiclient_exchange_rates_api = require "openapiclient.api.exchange_rates_api"
  -- unit tests for get_specific_rate
  describe("get_specific_rate test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for v1_exchangerate_asset_id_base_asset_id_quote_history_get
  describe("v1_exchangerate_asset_id_base_asset_id_quote_history_get test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for v1_exchangerate_asset_id_base_get
  describe("v1_exchangerate_asset_id_base_get test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for v1_exchangerate_history_periods_get
  describe("v1_exchangerate_history_periods_get test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
